use crate::frontend::ast;
use crate::frontend::Symbol;
use crate::frontend::tokens::{Token, LexicalError};
use crate::types::Type;

grammar;

// ...

extern {
  type Location = usize;
  type Error = LexicalError;

  enum Token {
    "DEF" => Token::KeywordDef,
    "VAR" => Token::KeywordVar,
    "INT" => Token::KeywordInt,
    "BOOL" => Token::KeywordBool,
    "VOID" => Token::KeywordVoid,
    "RETURN" => Token::KeywordReturn,
    "IF" => Token::KeywordIf,
    "ELSE" => Token::KeywordElse,
    "WHILE" => Token::KeywordWhile,
    "BREAK" => Token::KeywordBreak,
    "CONTINUE" => Token::KeywordContinue,
    "TRUE" => Token::KeywordTrue,
    "FALSE" => Token::KeywordFalse,
    "IDENT" => Token::Identifier(<Symbol>),
    "NUMBER" => Token::Number(<i64>),
    "," => Token::Comma,
    "(" => Token::LParen,
    ")" => Token::RParen,
    "{" => Token::LCurlyParen,
    "}" => Token::RCurlyParen,
    "=" => Token::Assign,
    ";" => Token::Semicolon,
    ":" => Token::Colon,
    "+" => Token::OpPlus,
    "-" => Token::OpMinus,
    "*" => Token::OpStar,
    "/" => Token::OpSlash,
    "%" => Token::OpMod,
    "|" => Token::OpPipe,
    "^" => Token::OpCaret,
    "&" => Token::OpAmpersand,
    "~" => Token::OpTilde,
    "<<" => Token::OpLShift,
    ">>" => Token::OpRShift,
    "==" => Token::OpEq,
    "!=" => Token::OpNEq,
    "<" => Token::OpL,
    "<=" => Token::OpLTE,
    ">" => Token::OpG,
    ">=" => Token::OpGTE,
    "&&" => Token::OpLAnd,
    "||" => Token::OpLOr,
    "!" => Token::OpLNot,
  }
}


pub BX: ast::Program = {
  <decls:Declaration*> => ast::Program(decls)
}

Declaration: ast::Declaration = {
  <var_decl:VarDeclGlobal> => ast::Declaration::Variable(Box::new(var_decl)),

  "DEF" <proc_name:"IDENT"> "(" <proc_args:ProcArgs?> ")" <return_type:(":" <Type>)?> "{" <stmts:Statement*> "}"  => {
    ast::Declaration::Proc {
      proc_name: proc_name.into(),
      proc_args,
      return_type,
      block: Box::new(ast::Block(stmts)),
    }
  }
}

VarDeclGlobal: ast::Variable = {
  "VAR" <name:"IDENT"> "=" <value:Expression> <name_value_pair:("," <"IDENT"> "=" <Expression>)*> ":" <ty:Type> ";" => {
    let (mut names, mut values): (Vec<Symbol>, Vec<Box<ast::Expression>>) = name_value_pair.into_iter().unzip();
    names.insert(0, name);
    values.insert(0, value);
    ast::Variable {names, values, ty, scope: ast::ScopeState::Global}
  }
}

ProcArgs: Vec<(Symbol, Type)> = {
  <arg:"IDENT"> ":" <ty:Type> <mut arg_type_pair:("," <"IDENT"> ":" <Type>)*> => {
    arg_type_pair.insert(0, (arg, ty));
    arg_type_pair
  }
}

Type: Type = {
  "INT" => Type::Int,
  "BOOL" => Type::Bool, 
  "VOID" => Type::Void
}

Statement: ast::Statement = {
  <var_decl:VarDeclLocal> => ast::Statement::Variable(Box::new(var_decl)),

  <name:"IDENT"> "=" <value:Expression> ";" => {
    ast::Statement::Assignment { name: name.into(), value }
  },

  <expr:Expression> ";" => ast::Statement::Eval(expr),

  "RETURN" <expr:Expression?> ";" => ast::Statement::Return(expr),

  "{" <stmts:Statement*> "}" => ast::Statement::Block(Box::new(ast::Block(stmts))),

  <ifelse:IFElse> => ifelse,

  "WHILE" "(" <condition:Expression> ")" "{" <stmts:Statement*> "}" => {
    ast::Statement::While { condition, block: Box::new(ast::Block(stmts)) }
  },

  "BREAK" ";"=> ast::Statement::Jump(ast::JumpState::Break),

  "CONTINUE" ";" => ast::Statement::Jump(ast::JumpState::Continue),
}

VarDeclLocal: ast::Variable = {
  "VAR" <name:"IDENT"> "=" <value:Expression> <name_value_pair:("," <"IDENT"> "=" <Expression>)*> ":" <ty:Type> ";" => {
    let (mut names, mut values): (Vec<Symbol>, Vec<Box<ast::Expression>>) = name_value_pair.into_iter().unzip();
    names.insert(0, name);
    values.insert(0, value);
    ast::Variable {names, values, ty, scope: ast::ScopeState::Local}
  }
}

IFElse: ast::Statement = {
  "IF" "(" <condition:Expression> ")" "{" <then_block:Statement*> "}" <ifrest:IFRest> => {
    ast::Statement::If {
      condition,
      then_block: Box::new(ast::Block(then_block)),
      else_branch: ifrest,
    }
  },
}

IFRest: Option<Box<ast::Statement>> = {
    "ELSE" "{" <else_stmts:Statement*> "}" => {
        Some(Box::new(ast::Statement::Block(Box::new(ast::Block(else_stmts)))))
    },

    "ELSE" <ifelse:IFElse> => {
        Some(Box::new(ifelse))
    },

    => None,
};

Expression: Box<ast::Expression> = {
  #[precedence(level="1")]
  Term,
  ProcCall,

  #[precedence(level="10")] #[assoc(side="right")]
  "~" <value:Expression> => {
    Box::new(ast::Expression::UnaryOperation {
      operator: ast::Operator::Tilde,
      value,
      ty: None
    })
  },

  #[precedence(level="20")] #[assoc(side="right")]
  "-" <value:Expression> => {
    Box::new(ast::Expression::UnaryOperation {
      operator: ast::Operator::Neg,
      value,
      ty: None
    })
  },

  "!" <value:Expression> => {
    Box::new(ast::Expression::UnaryOperation {
      operator: ast::Operator::LNot,
      value,
      ty: None
    })
  },

  #[precedence(level="30")] #[assoc(side="left")]
  <lhs:Expression> "*" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Star,
      rhs,
      ty: None
    })
  },

  <lhs:Expression> "/" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Slash,
      rhs,
      ty: None
    })
  },

  <lhs:Expression> "%" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Mod,
      rhs,
      ty: None
    })
  },

  #[precedence(level="40")] #[assoc(side="left")]
  <lhs:Expression> "+" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Plus,
      rhs,
      ty: None
    })
  },

  <lhs:Expression> "-" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Minus,
      rhs,
      ty: None
    })
  },

  #[precedence(level="50")] #[assoc(side="left")]
  <lhs:Expression> "<<" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::LShift,
      rhs,
      ty: None
    })
  },

  <lhs:Expression> ">>" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::RShift,
      rhs,
      ty: None
    })
  },

  #[precedence(level="53")] #[assoc(side="none")]
  <lhs:Expression> "<" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::L,
      rhs,
      ty: None
    })
  },

  <lhs:Expression> "<=" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::LTE,
      rhs,
      ty: None
    })
  },

  <lhs:Expression> ">" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::G,
      rhs,
      ty: None
    })
  },

  <lhs:Expression> ">=" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::GTE,
      rhs,
      ty: None
    })
  },

  #[precedence(level="56")] #[assoc(side="none")]
  <lhs:Expression> "==" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Equal,
      rhs,
      ty: None
    })
  },

  <lhs:Expression> "!=" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::NEqual,
      rhs,
      ty: None
    })
  },

  #[precedence(level="60")] #[assoc(side="left")]
  <lhs:Expression> "&" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Ampersand,
      rhs,
      ty: None
    })
  },

  #[precedence(level="70")] #[assoc(side="left")]
  <lhs:Expression> "^" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Caret,
      rhs,
      ty: None
    })
  },

  #[precedence(level="80")] #[assoc(side="left")]
  <lhs:Expression> "|" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Pipe,
      rhs,
      ty: None
    })
  },

  #[precedence(level="83")] #[assoc(side="left")]
  <lhs:Expression> "&&" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::LAnd,
      rhs,
      ty: None
    })
  },

  #[precedence(level="86")] #[assoc(side="left")]
  <lhs:Expression> "||" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::LOr,
      rhs,
      ty: None
    })
  },
}

Term: Box<ast::Expression> = {
  <val:"NUMBER"> => {
    Box::new(ast::Expression::Number(val))
  },

  <name:"IDENT"> => {
    Box::new(ast::Expression::Variable(name.into(), None))
  },

  "TRUE" => {
    Box::new(ast::Expression::Bool(true))
  },

  "FALSE" => {
    Box::new(ast::Expression::Bool(false))
  },

  "(" <Expression> ")",
}

ProcCall: Box<ast::Expression> = {
  <proc_name:"IDENT"> "(" <proc_args:ProcCallArgs?> ")" => Box::new(ast::Expression::ProcCall {proc_name: proc_name.into(), proc_args, ty: None}),
}

ProcCallArgs: Vec<Box<ast::Expression>> = {
  <arg:Expression> <mut args:("," <Expression>)*> => {
    args.insert(0, arg);
    args
  }
}
