use crate::tokens::{Token, LexicalError};
use crate::ast;

grammar;

// ...

extern {
  type Location = usize;
  type Error = LexicalError;

  enum Token {
    "DEF" => Token::KeywordDef,
    "MAIN" => Token::KeywordMain,
    "VAR" => Token::KeywordVar,
    "INT" => Token::KeywordInt,
    "PRINT" => Token::KeywordPrint,
    "IDENT" => Token::Identifier(<String>),
    "NUMBER" => Token::Number(<i64>),
    "(" => Token::LParen,
    ")" => Token::RParen,
    "{" => Token::LCurlyParen,
    "}" => Token::RCurlyParen,
    "=" => Token::Assign,
    ";" => Token::Semicolon,
    ":" => Token::Colon,
    "+" => Token::OperatorAdd,
    "-" => Token::OperatorSub,
    "*" => Token::OperatorMul,
    "/" => Token::OperatorDiv,
    "%" => Token::OperatorMod,
    "|" => Token::OperatorOr,
    "^" => Token::OperatorXor,
    "&" => Token::OperatorAnd,
    "~" => Token::OperatorComp,
    "<<" => Token::OperatorLShift,
    ">>" => Token::OperatorRShift,
  }
}


pub BX: Vec<ast::Statement> = {
  "DEF" "MAIN" "(" ")" "{"  <stmts:Statement*> "}" => stmts
}

Statement: ast::Statement = {
  "VAR" <name:"IDENT"> "=" <value:Expression> ":" "INT" ";" => {
    ast::Statement::Variable { name, value }
  },
  <name:"IDENT"> "=" <value:Expression> ";" => {
    ast::Statement::Assignment { name, value }
  },
  "PRINT" "(" <value:Expression> ")" ";" => {
    ast::Statement::Print { value }
  },
}

Expression: Box<ast::Expression> = {
  #[precedence(level="1")]
  Term,

  #[precedence(level="10")] #[assoc(side="right")]
  "~" <value:Expression> => {
    Box::new(ast::Expression::UnaryOperation {
      operator: ast::Operator::Comp,
      value
    })
  },

  #[precedence(level="20")] #[assoc(side="right")]
  "-" <value:Expression> => {
    Box::new(ast::Expression::UnaryOperation {
      operator: ast::Operator::Sub,
      value
    })
  },

  #[precedence(level="30")] #[assoc(side="left")]
  <lhs:Expression> "*" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Mul,
      rhs
    })
  },

  <lhs:Expression> "/" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Div,
      rhs
    })
  },

  <lhs:Expression> "%" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Mod,
      rhs
    })
  },

  #[precedence(level="40")] #[assoc(side="left")]
  <lhs:Expression> "+" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Add,
      rhs
    })
  },

  <lhs:Expression> "-" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Sub,
      rhs
    })
  },

  #[precedence(level="50")] #[assoc(side="left")]
  <lhs:Expression> "<<" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::LShift,
      rhs
    })
  },

  <lhs:Expression> ">>" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::RShift,
      rhs
    })
  },

  #[precedence(level="60")] #[assoc(side="left")]
  <lhs:Expression> "&" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::And,
      rhs
    })
  },

  #[precedence(level="70")] #[assoc(side="left")]
  <lhs:Expression> "^" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Xor,
      rhs
    })
  },

  #[precedence(level="80")] #[assoc(side="left")]
  <lhs:Expression> "|" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Or,
      rhs
    })
  },
}

Term: Box<ast::Expression> = {
  <val:"NUMBER"> => {
    Box::new(ast::Expression::Number(val))
  },
  <name:"IDENT"> => {
    Box::new(ast::Expression::Variable(name))
  },
  "(" <Expression> ")",
}
