use crate::tokens::{Token, LexicalError};
use crate::ast;

grammar;

// ...

extern {
  type Location = usize;
  type Error = LexicalError;

  enum Token {
    "DEF" => Token::KeywordDef,
    "MAIN" => Token::KeywordMain,
    "VAR" => Token::KeywordVar,
    "INT" => Token::KeywordInt,
    "PRINT" => Token::KeywordPrint,
    "IF" => Token::KeywordIf,
    "ELSE" => Token::KeywordElse,
    "WHILE" => Token::KeywordWhile,
    "BREAK" => Token::KeywordBreak,
    "CONTINUE" => Token::KeywordContinue,
    "TRUE" => Token::KeywordTrue,
    "FALSE" => Token::KeywordFalse,
    "IDENT" => Token::Identifier(<String>),
    "NUMBER" => Token::Number(<i64>),
    "(" => Token::LParen,
    ")" => Token::RParen,
    "{" => Token::LCurlyParen,
    "}" => Token::RCurlyParen,
    "=" => Token::Assign,
    ";" => Token::Semicolon,
    ":" => Token::Colon,
    "+" => Token::OpPlus,
    "-" => Token::OpMinus,
    "*" => Token::OpStar,
    "/" => Token::OpSlash,
    "%" => Token::OpMod,
    "|" => Token::OpPipe,
    "^" => Token::OpCaret,
    "&" => Token::OpAmpersand,
    "~" => Token::OpTilde,
    "<<" => Token::OpLShift,
    ">>" => Token::OpRShift,
    "==" => Token::OpEq,
    "!=" => Token::OpNEq,
    "<" => Token::OpL,
    "<=" => Token::OpLTE,
    ">" => Token::OpG,
    ">=" => Token::OpGTE,
    "&&" => Token::OpLAnd,
    "||" => Token::OpLOr,
    "!" => Token::OpLNot,
  }
}


pub BX: ast::Program = {
  "DEF" "MAIN" "(" ")" "{"  <stmts:Statement*> "}" => ast::Block(stmts)
}

IFElse: ast::Statement = {
  "IF" "(" <condition:Expression> ")" "{" <then_block:Statement*> "}" <ifrest:IFRest> => {
    ast::Statement::If {
      condition,
      then_block: Box::new(ast::Block(then_block)),
      else_branch: ifrest,
    }
  },
}

IFRest: Option<Box<ast::Statement>> = {
    "ELSE" "{" <else_stmts:Statement*> "}" => {
        Some(Box::new(ast::Statement::Block(Box::new(ast::Block(else_stmts)))))
    },

    "ELSE" <ifelse:IFElse> => {
        Some(Box::new(ifelse))
    },

    => None,
};

Statement: ast::Statement = {
  "VAR" <name:"IDENT"> "=" <value:Expression> ":" "INT" ";" => {
    ast::Statement::Variable { name, value }
  },

  <name:"IDENT"> "=" <value:Expression> ";" => {
    ast::Statement::Assignment { name, value }
  },

  "PRINT" "(" <value:Expression> ")" ";" => {
    ast::Statement::Print { value }
  },

  "{" <stmts:Statement*> "}" => ast::Statement::Block(Box::new(ast::Block(stmts))),

  <ifelse:IFElse> => ifelse,

  "WHILE" "(" <condition:Expression> ")" "{" <stmts:Statement*> "}" => {
    ast::Statement::While { condition, block: Box::new(ast::Block(stmts)) }
  },

  "BREAK" ";"=> ast::Statement::Jump(ast::JumpState::Break),

  "CONTINUE" ";" => ast::Statement::Jump(ast::JumpState::Continue),
}

Expression: Box<ast::Expression> = {
  #[precedence(level="1")]
  Term,

  #[precedence(level="10")] #[assoc(side="right")]
  "~" <value:Expression> => {
    Box::new(ast::Expression::UnaryOperation {
      operator: ast::Operator::Tilde,
      value
    })
  },

  #[precedence(level="20")] #[assoc(side="right")]
  "-" <value:Expression> => {
    Box::new(ast::Expression::UnaryOperation {
      operator: ast::Operator::Neg,
      value
    })
  },

  "!" <value:Expression> => {
    Box::new(ast::Expression::UnaryOperation {
      operator: ast::Operator::LNot,
      value
    })
  },

  #[precedence(level="30")] #[assoc(side="left")]
  <lhs:Expression> "*" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Star,
      rhs
    })
  },

  <lhs:Expression> "/" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Slash,
      rhs
    })
  },

  <lhs:Expression> "%" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Mod,
      rhs
    })
  },

  #[precedence(level="40")] #[assoc(side="left")]
  <lhs:Expression> "+" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Plus,
      rhs
    })
  },

  <lhs:Expression> "-" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Minus,
      rhs
    })
  },

  #[precedence(level="50")] #[assoc(side="left")]
  <lhs:Expression> "<<" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::LShift,
      rhs
    })
  },

  <lhs:Expression> ">>" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::RShift,
      rhs
    })
  },

  #[precedence(level="53")] #[assoc(side="none")]
  <lhs:Expression> "<" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::L,
      rhs
    })
  },

  <lhs:Expression> "<=" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::LTE,
      rhs
    })
  },

  <lhs:Expression> ">" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::G,
      rhs
    })
  },

  <lhs:Expression> ">=" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::GTE,
      rhs
    })
  },

  #[precedence(level="56")] #[assoc(side="none")]
  <lhs:Expression> "==" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Equal,
      rhs
    })
  },

  <lhs:Expression> "!=" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::NEqual,
      rhs
    })
  },

  #[precedence(level="60")] #[assoc(side="left")]
  <lhs:Expression> "&" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Ampersand,
      rhs
    })
  },

  #[precedence(level="70")] #[assoc(side="left")]
  <lhs:Expression> "^" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Caret,
      rhs
    })
  },

  #[precedence(level="80")] #[assoc(side="left")]
  <lhs:Expression> "|" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::Pipe,
      rhs
    })
  },

  #[precedence(level="83")] #[assoc(side="left")]
  <lhs:Expression> "&&" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::LAnd,
      rhs
    })
  },

  #[precedence(level="86")] #[assoc(side="left")]
  <lhs:Expression> "||" <rhs:Expression> => {
    Box::new(ast::Expression::BinaryOperation {
      lhs,
      operator: ast::Operator::LOr,
      rhs
    })
  },
}

Term: Box<ast::Expression> = {
  <val:"NUMBER"> => {
    Box::new(ast::Expression::Number(val))
  },

  <name:"IDENT"> => {
    Box::new(ast::Expression::Variable(name))
  },

  "TRUE" => {
    Box::new(ast::Expression::Bool(true))
  },

  "FALSE" => {
    Box::new(ast::Expression::Bool(false))
  },

  "(" <Expression> ")",
}
